
 .----------------.  .----------------.  .----------------.  .----------------.  .----------------.   
| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |  
| | ____    ____ | || |     _____    | || |  ________    | || |      __      | || |    _______   | |  
| ||_   \  /   _|| || |    |_   _|   | || | |_   ___ `.  | || |     /  \     | || |   /  ___  |  | |  
| |  |   \/   |  | || |      | |     | || |   | |   `. \ | || |    / /\ \    | || |  |  (__ \_|  | |  
| |  | |\  /| |  | || |      | |     | || |   | |    | | | || |   / ____ \   | || |   '.___`-.   | |  
| | _| |_\/_| |_ | || |     _| |_    | || |  _| |___.' / | || | _/ /    \ \_ | || |  |`\____) |  | |  
| ||_____||_____|| || |    |_____|   | || | |________.'  | || ||____|  |____|| || |  |_______.'  | |  
| |              | || |              | || |              | || |              | || |              | |  
| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |  
 '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  

MIDAS Version 0.2.1


====================================================================================================

ERROR: An error in the MIDAS execution has occurred with the following message: 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Traceback (most recent call last):
  File "/home/gkdelipe/midas/MIDAS/midas/utils/decorators.py", line 19, in wrapper
    exitcode = func(*args, **kwargs)
  File "/home/gkdelipe/midas/MIDAS/midas/utils/decorators.py", line 34, in wrapper
    result = func(*args, **kwargs)
  File "/home/gkdelipe/midas/MIDAS/midas/utils/decorators.py", line 47, in wrapper
    result = func(*args, **kwargs)
  File "/home/gkdelipe/midas/MIDAS/midasmain.py", line 85, in main
    inp_lines = Input_Parser(args.cpus, args.input)
  File "/home/gkdelipe/midas/MIDAS/midas/input_parser.py", line 425, in __init__
    self.parse_input_data()
  File "/home/gkdelipe/midas/MIDAS/midas/input_parser.py", line 460, in parse_input_data
    self.genome = yaml_line_reader(self.file_settings['decision_variables'], 'parameters', None)
  File "/home/gkdelipe/midas/MIDAS/midas/input_parser.py", line 26, in yaml_line_reader
    parsed_val = validate_input(keyword, parsed_val)
  File "/home/gkdelipe/midas/MIDAS/midas/input_parser.py", line 327, in validate_input
    raise ValueError(f"Decision variable '{key}' includes a constraint but no 'value' parameter.")
ValueError: Decision variable 'FA420IFBA064' includes a constraint but no 'value' parameter.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

MIDAS execution completed.
